@startuml

namespace WireCommon {
    interface IWireCommunicator {
        Action<Exception> HandleError
        Action<string> HandleMessage
        --
        void Error(Exception exception)
        void Message(string message)
    }
}

@enduml